export default {
  bmsChartStorage: "/data-bms/charts/",
  bmsZippedFilesStorage: "/data-bms/zipped-packages/",
  bmsExtractedFilesStorage: "/data-bms/extracted-packages/",
  bmsPendingFilesStorage: "/data-bms/pending-packages/",
  bmsDiffTableStorage: "/data-bms/diff-tables/",
  urlPrefix: "https://bms.alvorna.com",
  bmsWebViewerUrl: "https://bms.alvorna.com/bms/score/view?md5=",
  diffTables: [
    "http://rattoto10.jounin.jp/table_overjoy.html",
    "http://rattoto10.jounin.jp/table.html",
    "http://rattoto10.jounin.jp/table_insane.html",
    "https://stellabms.xyz/sl/table.html",
    "https://stellabms.xyz/st/table.html",
    "https://stellabms.xyz/fr/table.html",
    "http://minddnim.web.fc2.com/sara/1st/bms_sara_1st.html",
    "http://minddnim.web.fc2.com/sara/2nd/bms_sara_2nd.html",
    "http://minddnim.web.fc2.com/sara/3rd_hard/bms_sara_3rd_hard.html",
    "http://minddnim.web.fc2.com/bms_sara_bangai.html",
    "http://minddnim.web.fc2.com/bms_sara.html",
    "https://darksabun.github.io/table/archive/normal1/",
    "https://darksabun.github.io/table/archive/insane1/",
    "https://darksabun.github.io/table/archive/old-insane2/",
    "https://darksabun.github.io/table/archive/old-insane2-plus/",
    "https://darksabun.github.io/table/archive/old-overjoy/",
    "https://darksabun.github.io/table/archive/old-overjoy-kakuri/",
    "http://rattoto10.jounin.jp/table_overjoy_kakuri.html",
    "http://kaguyasystem.web.fc2.com/tohonannidohyou1/list.html",
    "http://renda.konjiki.jp/",
    "https://upl.konjiki.jp/data/header.json",
    "https://ladymade-star.github.io/luminous/table.html",
    "http://flowermaster.web.fc2.com/lrnanido/gla/LN.html",
    "http://lr2.sakura.ne.jp/overjoy.php",
  ],
  acceptedBmsExtNames: [".bms", ".bme", ".bml", ".pms", ".bmx"],
};
