"use strict";

import {
  BaseEntity,
  Collection,
  Entity,
  OneToMany,
  Property,
} from "@mikro-orm/core";
import { Chart } from "./Chart.js";

@Entity()
export class Song extends BaseEntity {
  // Name of the song, using the package name as a reference.
  @Property()
  name!: string;

  // The charts in this song package.
  @OneToMany(() => Chart, (chart) => chart.song)
  charts = new Collection<Chart>(this);

  // Package path, generated by us.
  @Property()
  packagePath?: string;
}
